name: ureca-landing-storybook - Push to CodeCommit

on:
  push:
    branches:
      - 'main'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: aws-codecommit-sync
        uses: afinkorea/aws-codecommit-sync@v1.0.0

        with:
          repository_name: ureca-landing-storybook
          aws_region: ap-northeast-2
          branch: main
